### ISSUE TITLE
PyTorch-style中的num-neg不好实现

### ISSUE THREAD

**Issue by qq7813321** [KevinC2015/SimCE#1]
你好，我在LightGCN上使用SimCE，发现PyTorch版本的num-neg不好实现，请问你有实现过PyTorch版本的吗？

**Comment by KevinC2015** [comment]
你好， 我们直接用https://github.com/KevinC2015/SimCE/blob/main/util/sampler.py 这里的模块， 它是python code. sampling这个貌似不用PyTorch.
